apiVersion: v1
kind: Namespace
metadata:
  name: red

---

apiVersion: v1
kind: Namespace
metadata:
  name: green

---

apiVersion: v1
kind: Namespace
metadata:
  name: blue

---

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---

apiVersion: v1
kind: Namespace
metadata:
  name: colour