apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    run: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-cm
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-sec
          mountPath: /usr/share/nginx/html/secret.html
          subPath: secret.html
      volumes:
        - name: nginx-cm
          configMap:
            name: nginx-cm
        - name: nginx-sec
          secret:
            secretName: nginx-sec